Fix FAB while scrolling on Dashboard
devclub-iitd/ShareACab pull request #162
Opened 2020-12-12 14:34 UTC by rish07

Fixes #145 

Here's a demo:
![untitled](https://user-images.githubusercontent.com/49035175/101986675-3c19c100-3cb5-11eb-979d-481b8c238c45.gif)

Please let me know if there are any changes @kshitijalwadhi

2020-12-12 14:38 UTC, Deepanshu-Rohilla commented
Hey @rish07 . Please attach some GIF's to demonstrate the changes (similar to screenshots in your previous PR).

2020-12-12 14:43 UTC, kshitijalwadhi requested changes
@rish07 
Please ensure that your hardwrap settings is set at 900. There seems to be some extra changes in the files changed. 
Also, execute `flutter analyze` before submitting your pull request and fix the bugs it suggests. You current PR is failing that check and suggesting this:
`Omit type annotations for local variables • lib/screens/tripslist.dart:26:5 • omit_local_variable_types`

2020-12-12 14:45 UTC, rish07 commented
@kshitijalwadhi will fix the flutter analyze bug but I can't seem to find the hard wrapping option in my Android Studio:

![image](https://user-images.githubusercontent.com/49035175/101986877-b72fa700-3cb6-11eb-96a0-0cadfa0ee33e.png)

2020-12-12 14:46 UTC, kshitijalwadhi commented
You are at the correct place afaik. Try changing that 80 to 900 and save the files again.

2020-12-12 14:52 UTC, rish07 commented
@Deepanshu-Rohilla 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/49035175/101987044-b6e3db80-3cb7-11eb-85e3-937603f240f2.gif)

2020-12-12 14:55 UTC, rish07 commented
@kshitijalwadhi Changed it to 900 and fixed the analyze bug.

2020-12-12 14:57 UTC, kshitijalwadhi commented
The problem with hard-wrap still seems to be there.
@Deepanshu-Rohilla can you guide him how to fix that in Android Studio? 
I have only worked on VS Code.

2020-12-12 15:08 UTC, rish07 commented
@kshitijalwadhi one way to fix it is to merge this PR, pull the new code on your system, change the formatting and push the changes as an amend to my previous commit

2020-12-12 15:08 UTC, Deepanshu-Rohilla commented
![Screenshot 2020-12-12 at 20 32 17](https://user-images.githubusercontent.com/52520071/101987280-227a7880-3cb9-11eb-997b-a1f6cd2642a2.png)
@rish07 This is the setting in my machine currently (macOS). 
Make sure that after changing the settings from 80 to 900, you've again reformatted the changed files (using `reformat code with dartfmt` option).
If the problem still persists, you check https://github.com/devclub-iitd/ShareACab/blob/master/CONTRIBUTING.md for stackoverflow links.

2020-12-12 15:11 UTC, rish07 commented
![image](https://user-images.githubusercontent.com/49035175/101987463-3ffc1200-3cba-11eb-9b28-bd73db314c12.png)

@Deepanshu-Rohilla There doesn't seem to be any such option in my version of the Android Studio(4.1.1).

2020-12-12 15:13 UTC, kshitijalwadhi requested changes
There are some issues with the way you have implemented this. The scrolling is jittery and it keeps bringing me back to the top when scrolling up. Have a look at the GIF attached. Maybe you will have to look more into its implementation.

![20201212_203950](https://user-images.githubusercontent.com/52427677/101987528-923d3300-3cba-11eb-8048-85f49e95317a.gif)

2020-12-12 15:16 UTC, rish07 commented
Ah right @kshitijalwadhi just saw it on my physical device. Let me find another approach to this. The problem is FAB is on Dashboard widget but the scrolling in the triplist.dart. So even tho I can detect the scroll direction in the child, the only way I can update the state of the parent is to call a function that sets the state of the Dashboard widget. That is what I have done here, I am not sure why is it setting states abruptly. Do you have any approach in mind?

2020-12-12 15:17 UTC, Deepanshu-Rohilla commented on lib/screens/dashboard.dart
> +
Calling refreshState makes the screen go to top. Make sure you don't use it whenever someone scrolls down.

2020-12-12 15:19 UTC, rish07 commented
@kshitijalwadhi fixed the hard wrapping issue

2020-12-12 15:20 UTC, rish07 commented on lib/screens/tripslist.dart
> +                widget.refreshParent();
@Deepanshu-Rohilla it is only being called when the direction of the scroll changes

2020-12-12 15:22 UTC, rish07 commented on lib/screens/dashboard.dart
> +                floatingActionButton: globals.scrollDirection ==
And if I don't call set state it won't get the new value of globals.scrollDirection

2020-12-12 15:30 UTC, rish07 commented
I would suggest moving the FAB on triplist.dart, so we can access setState only when needed. Or do let me know if there's any other approch

2020-12-12 15:39 UTC, Deepanshu-Rohilla commented
Try out the approach that you think might work out.

2020-12-14 12:37 UTC, tmibvishal commented
Closing this pull request now. Because this feature was already added in another pr.

2020-12-14 12:37 UTC, closed without merging